import { Onest } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";

const onest = Onest({ subsets: ["latin"] });

export const metadata = {
    title: "Bobolog",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="bg-slate-900">
            <body className={`${onest.className} antialiased`}>
                <HeroUIProvider>{children}</HeroUIProvider>
            </body>
        </html>
    );
}
